// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sleeper-designs/DarkHacker.tsx": () => import("../components/mockups/sleeper-designs/DarkHacker.tsx"),
  "./components/mockups/sleeper-designs/Signal.tsx": () => import("../components/mockups/sleeper-designs/Signal.tsx"),
  "./components/mockups/sleeper-designs/Studio.tsx": () => import("../components/mockups/sleeper-designs/Studio.tsx")
};
